# Generated by Django 3.1.6 on 2021-02-12 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dinner',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dish', models.CharField(default='', max_length=50)),
                ('cuisine', models.CharField(default='Norwegian', max_length=50)),
                ('date', models.DateTimeField()),
                ('location', models.CharField(max_length=100)),
                ('owner', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
