# Generated by Django 3.1.6 on 2021-03-14 19:03

from django.db import migrations


def initial_allergies(apps, schema_editor):
    Allergy = apps.get_model('dine_backend', 'Allergy')
    molluscs = Allergy(id=1, allergy="bløtdyr")
    molluscs.save()
    egg = Allergy(id=2, allergy="egg")
    egg.save()
    fish = Allergy(id=3, allergy="fisk")
    fish.save()
    gluten = Allergy(id=4, allergy="gluten")
    gluten.save()
    lupin = Allergy(id=5, allergy="lupin")
    lupin.save()
    milk = Allergy(id=6, allergy="melk")
    milk.save()
    nuts = Allergy(id=7, allergy="nøtter")
    nuts.save()
    peanuts = Allergy(id=8, allergy="peanøtter")
    peanuts.save()
    cellery = Allergy(id=9, allergy="selleri")
    cellery.save()
    mustard = Allergy(id=10, allergy="sennep")
    mustard.save()
    sesame = Allergy(id=11, allergy="sesam")
    sesame.save()
    shellfish = Allergy(id=12, allergy="skalldyr")
    shellfish.save()
    soya = Allergy(id=13, allergy="soya")
    soya.save()
    sulfites = Allergy(id=14, allergy="sulfitter")
    sulfites.save()


class Migration(migrations.Migration):

    dependencies = [
        ('dine_backend', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(initial_allergies),
    ]
