# Generated by Django 3.1.6 on 2021-03-08 16:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dine_backend', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dinner',
            name='description',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='cuisine',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='dish',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='dinner',
            name='owner',
            field=models.CharField(max_length=50),
        ),
        migrations.CreateModel(
            name='DinnerAllergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(max_length=50)),
                ('dinner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dine_backend.dinner')),
            ],
        ),
    ]
