# Generated by Django 3.1.6 on 2021-03-08 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_backend', '0002_auto_20210308_1659'),
    ]

    operations = [
        migrations.CreateModel(
            name='Allergy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('allergy', models.CharField(max_length=50)),
            ],
        ),
        migrations.DeleteModel(
            name='DinnerAllergy',
        ),
        migrations.AddField(
            model_name='dinner',
            name='allergies',
            field=models.ManyToManyField(to='dine_backend.Allergy'),
        ),
    ]
