# Generated by Django 3.1.6 on 2021-03-16 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dine_backend', '0003_auto_20210315_0929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
    ]
