# Generated by Django 3.1.6 on 2021-03-08 17:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_backend', '0004_auto_20210308_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='allergies',
            field=models.ManyToManyField(to='dine_backend.Allergy'),
        ),
    ]
