# Generated by Django 3.1.6 on 2021-03-08 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dine_backend', '0005_auto_20210308_1727'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dinner',
            name='allergies',
            field=models.ManyToManyField(blank=True, to='dine_backend.Allergy'),
        ),
    ]
